### ISSUE TITLE
React JS : Sticky Table Header is not working

### ISSUE THREAD

**Issue by ramu1224** [christopheraue/reactjs#3]
Hi,
I am trying to read a table header(Thead tag using id in DIV tag) from JSP & then applying a STICKYDIV, which has been created as a class using ReactJS & rendering on the same DIV.

While taking document.getElementId("TheadId") in React JS, it is reading the data as text instead of HTML code. How to read the data as HTML to create a component, which can be used in React JS Render function.

Thanks,
Ram

**Comment by christopheraue** [comment]
Hmm, this project does not deal with such stuff. Perhaps you intended to reach someone at https://github.com/facebook/react?
